"""empty message

Revision ID: 24bd1326f8b1
Revises: c689f84139a6
Create Date: 2022-03-10 16:55:22.530267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bd1326f8b1'
down_revision = 'c689f84139a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dist_to_bag', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dist_to_bag', 'status')
    # ### end Alembic commands ###
