"""empty message

Revision ID: 3073adfcd691
Revises: 822c316d5afb
Create Date: 2022-03-09 01:04:11.216584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3073adfcd691'
down_revision = '822c316d5afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bag', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bag', sa.Column('uid', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
