"""empty message

Revision ID: 418a8fd5d22b
Revises: 4636cf2e29a6
Create Date: 2022-03-09 00:02:54.268997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418a8fd5d22b'
down_revision = '4636cf2e29a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_to_bag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('bag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit.id'], ),
    sa.ForeignKeyConstraint(['bag_id'], ['bag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bag_to_audit_sku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bag_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bag_id'], ['bag.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['auditsku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bag_to_audit_sku')
    op.drop_table('audit_to_bag')
    # ### end Alembic commands ###
