"""empty message

Revision ID: 7a24579dba26
Revises: 3073adfcd691
Create Date: 2022-03-09 01:04:41.891604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a24579dba26'
down_revision = '3073adfcd691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bag', sa.Column('uid', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bag', 'uid')
    # ### end Alembic commands ###
