"""empty message

Revision ID: 822c316d5afb
Revises: 418a8fd5d22b
Create Date: 2022-03-09 01:00:44.414816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822c316d5afb'
down_revision = '418a8fd5d22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bag_ibfk_1', 'bag', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('bag_ibfk_1', 'bag', 'dist_vendor', ['uid'], ['id'])
    # ### end Alembic commands ###
