"""empty message

Revision ID: a1b4c1fca50c
Revises: 24bd1326f8b1
Create Date: 2022-03-10 21:47:44.743504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b4c1fca50c'
down_revision = '24bd1326f8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transporter_id', sa.Integer(), nullable=False),
    sa.Column('truck_number', sa.String(length=25), nullable=False),
    sa.Column('latitude', sa.String(length=50), nullable=False),
    sa.Column('longnitude', sa.String(length=50), nullable=False),
    sa.Column('dist_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('pickup_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dist_id'], ['dist_vendor.id'], ),
    sa.ForeignKeyConstraint(['transporter_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pick_to_bag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bag_id', sa.Integer(), nullable=False),
    sa.Column('pick_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bag_id'], ['bag.id'], ),
    sa.ForeignKeyConstraint(['pick_id'], ['pickup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pick_to_bag')
    op.drop_table('pickup')
    # ### end Alembic commands ###
