"""empty message

Revision ID: c689f84139a6
Revises: 7a24579dba26
Create Date: 2022-03-09 02:43:23.654173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c689f84139a6'
down_revision = '7a24579dba26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dist_to_bag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dist_id', sa.Integer(), nullable=False),
    sa.Column('bag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bag_id'], ['bag.id'], ),
    sa.ForeignKeyConstraint(['dist_id'], ['dist_vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dist_to_bag')
    # ### end Alembic commands ###
