"""empty message

Revision ID: f56014c18b45
Revises: f772129c0db1
Create Date: 2022-03-10 22:56:26.031940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56014c18b45'
down_revision = 'f772129c0db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport_vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_code', sa.String(length=50), nullable=False),
    sa.Column('vendor_name', sa.String(length=250), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('pin_code', sa.String(length=25), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.String(length=50), nullable=False),
    sa.Column('longnitude', sa.String(length=50), nullable=False),
    sa.Column('contact_person', sa.String(length=50), nullable=False),
    sa.Column('contact_number', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transtovendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['transport_vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transtovendor')
    op.drop_table('transport_vendor')
    # ### end Alembic commands ###
