"""empty message

Revision ID: f772129c0db1
Revises: a1b4c1fca50c
Create Date: 2022-03-10 21:54:50.781792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f772129c0db1'
down_revision = 'a1b4c1fca50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pick_to_bag', sa.Column('status', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pick_to_bag', 'status')
    # ### end Alembic commands ###
